// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Api.V4.Issues_statistics
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetScopeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "created_by_me")]
        #pragma warning disable CS1591
        Created_by_me,
        #pragma warning restore CS1591
        [EnumMember(Value = "assigned_to_me")]
        #pragma warning disable CS1591
        Assigned_to_me,
        #pragma warning restore CS1591
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
    }
}
