// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.GitLab.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Subgroups
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\groups\{id}\subgroups
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubgroupsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Subgroups.SubgroupsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SubgroupsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/groups/{id}/subgroups{?active*,all_available*,archived*,custom_attributes*,marked_for_deletion_on*,min_access_level*,order_by*,owned*,page*,per_page*,repository_storage*,search*,skip_groups,sort*,statistics*,top_level_only*,visibility*,with_custom_attributes*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Subgroups.SubgroupsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SubgroupsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/groups/{id}/subgroups{?active*,all_available*,archived*,custom_attributes*,marked_for_deletion_on*,min_access_level*,order_by*,owned*,page*,per_page*,repository_storage*,search*,skip_groups,sort*,statistics*,top_level_only*,visibility*,with_custom_attributes*}", rawUrl)
        {
        }
        /// <summary>
        /// Get a list of subgroups in this group.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesGroup"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesGroup?> GetAsync(Action<RequestConfiguration<global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Subgroups.SubgroupsRequestBuilder.SubgroupsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesGroup> GetAsync(Action<RequestConfiguration<global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Subgroups.SubgroupsRequestBuilder.SubgroupsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesGroup>(requestInfo, global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesGroup.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a list of subgroups in this group.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Subgroups.SubgroupsRequestBuilder.SubgroupsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Subgroups.SubgroupsRequestBuilder.SubgroupsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Subgroups.SubgroupsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Subgroups.SubgroupsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Subgroups.SubgroupsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get a list of subgroups in this group.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SubgroupsRequestBuilderGetQueryParameters 
        {
            /// <summary>Limit by groups that are not archived and not marked for deletion</summary>
            [QueryParameter("active")]
            public bool? Active { get; set; }
            /// <summary>When `true`, returns all accessible groups. When `false`, returns only groups where the user is a member.</summary>
            [QueryParameter("all_available")]
            public bool? AllAvailable { get; set; }
            /// <summary>Limit by archived status</summary>
            [QueryParameter("archived")]
            public bool? Archived { get; set; }
            /// <summary>Filter with custom attributes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("custom_attributes")]
            public string? CustomAttributes { get; set; }
#nullable restore
#else
            [QueryParameter("custom_attributes")]
            public string CustomAttributes { get; set; }
#endif
            /// <summary>Return groups that are marked for deletion on this date</summary>
            [QueryParameter("marked_for_deletion_on")]
            public Date? MarkedForDeletionOn { get; set; }
            /// <summary>Minimum access level of authenticated user</summary>
            [QueryParameter("min_access_level")]
            public int? MinAccessLevel { get; set; }
            /// <summary>Order by name, path, id or similarity if searching</summary>
            [Obsolete("This property is deprecated, use OrderByAsGetOrderByQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order_by")]
            public string? OrderBy { get; set; }
#nullable restore
#else
            [QueryParameter("order_by")]
            public string OrderBy { get; set; }
#endif
            /// <summary>Order by name, path, id or similarity if searching</summary>
            [QueryParameter("order_by")]
            public global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Subgroups.GetOrder_byQueryParameterType? OrderByAsGetOrderByQueryParameterType { get; set; }
            /// <summary>Limit by owned by authenticated user</summary>
            [QueryParameter("owned")]
            public bool? Owned { get; set; }
            /// <summary>Current page number</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>Number of items per page</summary>
            [QueryParameter("per_page")]
            public int? PerPage { get; set; }
            /// <summary>Filter by repository storage used by the group</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("repository_storage")]
            public string? RepositoryStorage { get; set; }
#nullable restore
#else
            [QueryParameter("repository_storage")]
            public string RepositoryStorage { get; set; }
#endif
            /// <summary>Search for a specific group</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search")]
            public string? Search { get; set; }
#nullable restore
#else
            [QueryParameter("search")]
            public string Search { get; set; }
#endif
            /// <summary>Array of group ids to exclude from list</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("skip_groups")]
            public int?[]? SkipGroups { get; set; }
#nullable restore
#else
            [QueryParameter("skip_groups")]
            public int?[] SkipGroups { get; set; }
#endif
            /// <summary>Sort by asc (ascending) or desc (descending)</summary>
            [Obsolete("This property is deprecated, use SortAsGetSortQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
            /// <summary>Sort by asc (ascending) or desc (descending)</summary>
            [QueryParameter("sort")]
            public global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Subgroups.GetSortQueryParameterType? SortAsGetSortQueryParameterType { get; set; }
            /// <summary>Include project statistics</summary>
            [QueryParameter("statistics")]
            public bool? Statistics { get; set; }
            /// <summary>Only include top-level groups</summary>
            [QueryParameter("top_level_only")]
            public bool? TopLevelOnly { get; set; }
            /// <summary>Limit by visibility</summary>
            [Obsolete("This property is deprecated, use VisibilityAsGetVisibilityQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("visibility")]
            public string? Visibility { get; set; }
#nullable restore
#else
            [QueryParameter("visibility")]
            public string Visibility { get; set; }
#endif
            /// <summary>Limit by visibility</summary>
            [QueryParameter("visibility")]
            public global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Subgroups.GetVisibilityQueryParameterType? VisibilityAsGetVisibilityQueryParameterType { get; set; }
            /// <summary>Include custom attributes in the response</summary>
            [QueryParameter("with_custom_attributes")]
            public bool? WithCustomAttributes { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SubgroupsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Subgroups.SubgroupsRequestBuilder.SubgroupsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
