// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Api.V4.Projects.Item.Repository.Contributors
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrder_byQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "commits")]
        #pragma warning disable CS1591
        Commits,
        #pragma warning restore CS1591
    }
}
