// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class APIEntitiesDependency : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The dependency_file_path property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DependencyFilePath { get; set; }
#nullable restore
#else
        public string DependencyFilePath { get; set; }
#endif
        /// <summary>The licenses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitLab.OpenApiClient.Models.DependencyEntityLicenseEntity? Licenses { get; set; }
#nullable restore
#else
        public global::Soenneker.GitLab.OpenApiClient.Models.DependencyEntityLicenseEntity Licenses { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The package_manager property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PackageManager { get; set; }
#nullable restore
#else
        public string PackageManager { get; set; }
#endif
        /// <summary>The version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>The vulnerabilities property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitLab.OpenApiClient.Models.DependencyEntityVulnerabilityEntity? Vulnerabilities { get; set; }
#nullable restore
#else
        public global::Soenneker.GitLab.OpenApiClient.Models.DependencyEntityVulnerabilityEntity Vulnerabilities { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesDependency"/> and sets the default values.
        /// </summary>
        public APIEntitiesDependency()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesDependency"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesDependency CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesDependency();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dependency_file_path", n => { DependencyFilePath = n.GetStringValue(); } },
                { "licenses", n => { Licenses = n.GetObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.DependencyEntityLicenseEntity>(global::Soenneker.GitLab.OpenApiClient.Models.DependencyEntityLicenseEntity.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "package_manager", n => { PackageManager = n.GetStringValue(); } },
                { "version", n => { Version = n.GetStringValue(); } },
                { "vulnerabilities", n => { Vulnerabilities = n.GetObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.DependencyEntityVulnerabilityEntity>(global::Soenneker.GitLab.OpenApiClient.Models.DependencyEntityVulnerabilityEntity.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("dependency_file_path", DependencyFilePath);
            writer.WriteObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.DependencyEntityLicenseEntity>("licenses", Licenses);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("package_manager", PackageManager);
            writer.WriteStringValue("version", Version);
            writer.WriteObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.DependencyEntityVulnerabilityEntity>("vulnerabilities", Vulnerabilities);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
