// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApiEntitiesCiUserPipeline : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The detailed_status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitLab.OpenApiClient.Models.DetailedStatusEntity? DetailedStatus { get; set; }
#nullable restore
#else
        public global::Soenneker.GitLab.OpenApiClient.Models.DetailedStatusEntity DetailedStatus { get; set; }
#endif
        /// <summary>Time spent running in seconds</summary>
        public int? Duration { get; set; }
        /// <summary>The finished_at property</summary>
        public DateTimeOffset? FinishedAt { get; set; }
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The iid property</summary>
        public int? Iid { get; set; }
        /// <summary>The merge_request property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCiPipelineMergeRequest? MergeRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCiPipelineMergeRequest MergeRequest { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The project property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesProjectIdentity? Project { get; set; }
#nullable restore
#else
        public global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesProjectIdentity Project { get; set; }
#endif
        /// <summary>The project_id property</summary>
        public long? ProjectId { get; set; }
        /// <summary>Time spent queued in seconds</summary>
        public int? QueuedDuration { get; set; }
        /// <summary>The ref property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ref { get; set; }
#nullable restore
#else
        public string Ref { get; set; }
#endif
        /// <summary>The sha property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sha { get; set; }
#nullable restore
#else
        public string Sha { get; set; }
#endif
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>The started_at property</summary>
        public DateTimeOffset? StartedAt { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The web_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebUrl { get; set; }
#nullable restore
#else
        public string WebUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCiUserPipeline"/> and sets the default values.
        /// </summary>
        public ApiEntitiesCiUserPipeline()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCiUserPipeline"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCiUserPipeline CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCiUserPipeline();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "detailed_status", n => { DetailedStatus = n.GetObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.DetailedStatusEntity>(global::Soenneker.GitLab.OpenApiClient.Models.DetailedStatusEntity.CreateFromDiscriminatorValue); } },
                { "duration", n => { Duration = n.GetIntValue(); } },
                { "finished_at", n => { FinishedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "iid", n => { Iid = n.GetIntValue(); } },
                { "merge_request", n => { MergeRequest = n.GetObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCiPipelineMergeRequest>(global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCiPipelineMergeRequest.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "project", n => { Project = n.GetObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesProjectIdentity>(global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesProjectIdentity.CreateFromDiscriminatorValue); } },
                { "project_id", n => { ProjectId = n.GetLongValue(); } },
                { "queued_duration", n => { QueuedDuration = n.GetIntValue(); } },
                { "ref", n => { Ref = n.GetStringValue(); } },
                { "sha", n => { Sha = n.GetStringValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "started_at", n => { StartedAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "web_url", n => { WebUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.DetailedStatusEntity>("detailed_status", DetailedStatus);
            writer.WriteIntValue("duration", Duration);
            writer.WriteDateTimeOffsetValue("finished_at", FinishedAt);
            writer.WriteLongValue("id", Id);
            writer.WriteIntValue("iid", Iid);
            writer.WriteObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCiPipelineMergeRequest>("merge_request", MergeRequest);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesProjectIdentity>("project", Project);
            writer.WriteLongValue("project_id", ProjectId);
            writer.WriteIntValue("queued_duration", QueuedDuration);
            writer.WriteStringValue("ref", Ref);
            writer.WriteStringValue("sha", Sha);
            writer.WriteStringValue("source", Source);
            writer.WriteDateTimeOffsetValue("started_at", StartedAt);
            writer.WriteStringValue("status", Status);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteStringValue("web_url", WebUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
