// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApiEntitiesMember : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The access_level property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessLevel { get; set; }
#nullable restore
#else
        public string AccessLevel { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The avatar_path property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AvatarPath { get; set; }
#nullable restore
#else
        public string AvatarPath { get; set; }
#endif
        /// <summary>The avatar_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AvatarUrl { get; set; }
#nullable restore
#else
        public string AvatarUrl { get; set; }
#endif
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The created_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesUserBasic? CreatedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesUserBasic CreatedBy { get; set; }
#endif
        /// <summary>The custom_attributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCustomAttribute>? CustomAttributes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCustomAttribute> CustomAttributes { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The expires_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExpiresAt { get; set; }
#nullable restore
#else
        public string ExpiresAt { get; set; }
#endif
        /// <summary>The group_saml_identity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesIdentity? GroupSamlIdentity { get; set; }
#nullable restore
#else
        public global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesIdentity GroupSamlIdentity { get; set; }
#endif
        /// <summary>The group_scim_identity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesScimIdentity? GroupScimIdentity { get; set; }
#nullable restore
#else
        public global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesScimIdentity GroupScimIdentity { get; set; }
#endif
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The is_using_seat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IsUsingSeat { get; set; }
#nullable restore
#else
        public string IsUsingSeat { get; set; }
#endif
        /// <summary>The locked property</summary>
        public bool? Locked { get; set; }
        /// <summary>The member_role property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMemberRole? MemberRole { get; set; }
#nullable restore
#else
        public global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMemberRole MemberRole { get; set; }
#endif
        /// <summary>The membership_state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MembershipState { get; set; }
#nullable restore
#else
        public string MembershipState { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The override property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Override { get; set; }
#nullable restore
#else
        public string Override { get; set; }
#endif
        /// <summary>The public_email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicEmail { get; set; }
#nullable restore
#else
        public string PublicEmail { get; set; }
#endif
        /// <summary>The state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The username property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>The web_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebUrl { get; set; }
#nullable restore
#else
        public string WebUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMember"/> and sets the default values.
        /// </summary>
        public ApiEntitiesMember()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMember"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMember CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMember();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access_level", n => { AccessLevel = n.GetStringValue(); } },
                { "avatar_path", n => { AvatarPath = n.GetStringValue(); } },
                { "avatar_url", n => { AvatarUrl = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesUserBasic>(global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesUserBasic.CreateFromDiscriminatorValue); } },
                { "custom_attributes", n => { CustomAttributes = n.GetCollectionOfObjectValues<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCustomAttribute>(global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCustomAttribute.CreateFromDiscriminatorValue)?.AsList(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetStringValue(); } },
                { "group_saml_identity", n => { GroupSamlIdentity = n.GetObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesIdentity>(global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesIdentity.CreateFromDiscriminatorValue); } },
                { "group_scim_identity", n => { GroupScimIdentity = n.GetObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesScimIdentity>(global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesScimIdentity.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "is_using_seat", n => { IsUsingSeat = n.GetStringValue(); } },
                { "locked", n => { Locked = n.GetBoolValue(); } },
                { "member_role", n => { MemberRole = n.GetObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMemberRole>(global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMemberRole.CreateFromDiscriminatorValue); } },
                { "membership_state", n => { MembershipState = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "override", n => { Override = n.GetStringValue(); } },
                { "public_email", n => { PublicEmail = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "username", n => { Username = n.GetStringValue(); } },
                { "web_url", n => { WebUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("access_level", AccessLevel);
            writer.WriteStringValue("avatar_path", AvatarPath);
            writer.WriteStringValue("avatar_url", AvatarUrl);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesUserBasic>("created_by", CreatedBy);
            writer.WriteCollectionOfObjectValues<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCustomAttribute>("custom_attributes", CustomAttributes);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("expires_at", ExpiresAt);
            writer.WriteObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesIdentity>("group_saml_identity", GroupSamlIdentity);
            writer.WriteObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesScimIdentity>("group_scim_identity", GroupScimIdentity);
            writer.WriteLongValue("id", Id);
            writer.WriteStringValue("is_using_seat", IsUsingSeat);
            writer.WriteBoolValue("locked", Locked);
            writer.WriteObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMemberRole>("member_role", MemberRole);
            writer.WriteStringValue("membership_state", MembershipState);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("override", Override);
            writer.WriteStringValue("public_email", PublicEmail);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("username", Username);
            writer.WriteStringValue("web_url", WebUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
