// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class APIEntitiesIssuableTimeStats : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The human_time_estimate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HumanTimeEstimate { get; set; }
#nullable restore
#else
        public string HumanTimeEstimate { get; set; }
#endif
        /// <summary>The human_total_time_spent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HumanTotalTimeSpent { get; set; }
#nullable restore
#else
        public string HumanTotalTimeSpent { get; set; }
#endif
        /// <summary>The time_estimate property</summary>
        public int? TimeEstimate { get; set; }
        /// <summary>The total_time_spent property</summary>
        public int? TotalTimeSpent { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesIssuableTimeStats"/> and sets the default values.
        /// </summary>
        public APIEntitiesIssuableTimeStats()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesIssuableTimeStats"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesIssuableTimeStats CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesIssuableTimeStats();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "human_time_estimate", n => { HumanTimeEstimate = n.GetStringValue(); } },
                { "human_total_time_spent", n => { HumanTotalTimeSpent = n.GetStringValue(); } },
                { "time_estimate", n => { TimeEstimate = n.GetIntValue(); } },
                { "total_time_spent", n => { TotalTimeSpent = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("human_time_estimate", HumanTimeEstimate);
            writer.WriteStringValue("human_total_time_spent", HumanTotalTimeSpent);
            writer.WriteIntValue("time_estimate", TimeEstimate);
            writer.WriteIntValue("total_time_spent", TotalTimeSpent);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
