// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class APIEntitiesPackagesConanPackageSnapshot : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The package_snapshot property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesPackagesConanPackageSnapshot_package_snapshot? PackageSnapshot { get; set; }
#nullable restore
#else
        public global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesPackagesConanPackageSnapshot_package_snapshot PackageSnapshot { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesPackagesConanPackageSnapshot"/> and sets the default values.
        /// </summary>
        public APIEntitiesPackagesConanPackageSnapshot()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesPackagesConanPackageSnapshot"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesPackagesConanPackageSnapshot CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesPackagesConanPackageSnapshot();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "package_snapshot", n => { PackageSnapshot = n.GetObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesPackagesConanPackageSnapshot_package_snapshot>(global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesPackagesConanPackageSnapshot_package_snapshot.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesPackagesConanPackageSnapshot_package_snapshot>("package_snapshot", PackageSnapshot);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
