// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class APIEntitiesUserCounts : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The assigned_issues property</summary>
        public int? AssignedIssues { get; set; }
        /// <summary>The assigned_merge_requests property</summary>
        public int? AssignedMergeRequests { get; set; }
        /// <summary>The merge_requests property</summary>
        public int? MergeRequests { get; set; }
        /// <summary>The review_requested_merge_requests property</summary>
        public int? ReviewRequestedMergeRequests { get; set; }
        /// <summary>The todos property</summary>
        public int? Todos { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesUserCounts"/> and sets the default values.
        /// </summary>
        public APIEntitiesUserCounts()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesUserCounts"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesUserCounts CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesUserCounts();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assigned_issues", n => { AssignedIssues = n.GetIntValue(); } },
                { "assigned_merge_requests", n => { AssignedMergeRequests = n.GetIntValue(); } },
                { "merge_requests", n => { MergeRequests = n.GetIntValue(); } },
                { "review_requested_merge_requests", n => { ReviewRequestedMergeRequests = n.GetIntValue(); } },
                { "todos", n => { Todos = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("assigned_issues", AssignedIssues);
            writer.WriteIntValue("assigned_merge_requests", AssignedMergeRequests);
            writer.WriteIntValue("merge_requests", MergeRequests);
            writer.WriteIntValue("review_requested_merge_requests", ReviewRequestedMergeRequests);
            writer.WriteIntValue("todos", Todos);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
