// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class APIEntitiesRepositoryHealthObjects : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cruft_count property</summary>
        public int? CruftCount { get; set; }
        /// <summary>The keep_count property</summary>
        public int? KeepCount { get; set; }
        /// <summary>The keep_size property</summary>
        public int? KeepSize { get; set; }
        /// <summary>The loose_objects_count property</summary>
        public int? LooseObjectsCount { get; set; }
        /// <summary>The loose_objects_garbage_count property</summary>
        public int? LooseObjectsGarbageCount { get; set; }
        /// <summary>The packfile_count property</summary>
        public int? PackfileCount { get; set; }
        /// <summary>The recent_size property</summary>
        public int? RecentSize { get; set; }
        /// <summary>The reverse_index_count property</summary>
        public int? ReverseIndexCount { get; set; }
        /// <summary>The size property</summary>
        public int? Size { get; set; }
        /// <summary>The stale_loose_objects_count property</summary>
        public int? StaleLooseObjectsCount { get; set; }
        /// <summary>The stale_size property</summary>
        public int? StaleSize { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesRepositoryHealthObjects"/> and sets the default values.
        /// </summary>
        public APIEntitiesRepositoryHealthObjects()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesRepositoryHealthObjects"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesRepositoryHealthObjects CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesRepositoryHealthObjects();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cruft_count", n => { CruftCount = n.GetIntValue(); } },
                { "keep_count", n => { KeepCount = n.GetIntValue(); } },
                { "keep_size", n => { KeepSize = n.GetIntValue(); } },
                { "loose_objects_count", n => { LooseObjectsCount = n.GetIntValue(); } },
                { "loose_objects_garbage_count", n => { LooseObjectsGarbageCount = n.GetIntValue(); } },
                { "packfile_count", n => { PackfileCount = n.GetIntValue(); } },
                { "recent_size", n => { RecentSize = n.GetIntValue(); } },
                { "reverse_index_count", n => { ReverseIndexCount = n.GetIntValue(); } },
                { "size", n => { Size = n.GetIntValue(); } },
                { "stale_loose_objects_count", n => { StaleLooseObjectsCount = n.GetIntValue(); } },
                { "stale_size", n => { StaleSize = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("cruft_count", CruftCount);
            writer.WriteIntValue("keep_count", KeepCount);
            writer.WriteIntValue("keep_size", KeepSize);
            writer.WriteIntValue("loose_objects_count", LooseObjectsCount);
            writer.WriteIntValue("loose_objects_garbage_count", LooseObjectsGarbageCount);
            writer.WriteIntValue("packfile_count", PackfileCount);
            writer.WriteIntValue("recent_size", RecentSize);
            writer.WriteIntValue("reverse_index_count", ReverseIndexCount);
            writer.WriteIntValue("size", Size);
            writer.WriteIntValue("stale_loose_objects_count", StaleLooseObjectsCount);
            writer.WriteIntValue("stale_size", StaleSize);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
