// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetApiV4GroupsIdDoraMetricsEnvironmentTiersParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "production")]
        #pragma warning disable CS1591
        Production,
        #pragma warning restore CS1591
        [EnumMember(Value = "staging")]
        #pragma warning disable CS1591
        Staging,
        #pragma warning restore CS1591
        [EnumMember(Value = "testing")]
        #pragma warning disable CS1591
        Testing,
        #pragma warning restore CS1591
        [EnumMember(Value = "development")]
        #pragma warning disable CS1591
        Development,
        #pragma warning restore CS1591
        [EnumMember(Value = "other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
    }
}
