// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostApiV4OrbitQueryNameRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Named query parameters</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitLab.OpenApiClient.Models.PostApiV4OrbitQueryNameRequestParametersProperty? Parameters { get; set; }
#nullable restore
#else
        public global::Soenneker.GitLab.OpenApiClient.Models.PostApiV4OrbitQueryNameRequestParametersProperty Parameters { get; set; }
#endif
        /// <summary>Response format: raw, llm, or gql</summary>
        public global::Soenneker.GitLab.OpenApiClient.Models.PostApiV4OrbitQueryNameRequestResponseFormat? ResponseFormat { get; set; }
        /// <summary>Optional frontend source subtype (e.g. code_intelligence)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceType { get; set; }
#nullable restore
#else
        public string SourceType { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.PostApiV4OrbitQueryNameRequest"/> and sets the default values.
        /// </summary>
        public PostApiV4OrbitQueryNameRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.PostApiV4OrbitQueryNameRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.PostApiV4OrbitQueryNameRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.PostApiV4OrbitQueryNameRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "parameters", n => { Parameters = n.GetObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.PostApiV4OrbitQueryNameRequestParametersProperty>(global::Soenneker.GitLab.OpenApiClient.Models.PostApiV4OrbitQueryNameRequestParametersProperty.CreateFromDiscriminatorValue); } },
                { "response_format", n => { ResponseFormat = n.GetEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.PostApiV4OrbitQueryNameRequestResponseFormat>(); } },
                { "source_type", n => { SourceType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.PostApiV4OrbitQueryNameRequestParametersProperty>("parameters", Parameters);
            writer.WriteEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.PostApiV4OrbitQueryNameRequestResponseFormat>("response_format", ResponseFormat);
            writer.WriteStringValue("source_type", SourceType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
