// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PutApiV4ProjectsIdFeatureFlagsFeatureFlagNameRequestStrategiesItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>If `true`, deletes the strategy.</summary>
        public bool? Destroy { get; set; }
        /// <summary>ID of the feature flag strategy.</summary>
        public int? Id { get; set; }
        /// <summary>Name of the strategy.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Strategy parameters as a JSON-formatted string, for example `{&quot;userIds&quot;:&quot;user1&quot;}`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitLab.OpenApiClient.Models.PutApiV4ProjectsIdFeatureFlagsFeatureFlagNameRequestStrategiesItemParametersProperty? Parameters { get; set; }
#nullable restore
#else
        public global::Soenneker.GitLab.OpenApiClient.Models.PutApiV4ProjectsIdFeatureFlagsFeatureFlagNameRequestStrategiesItemParametersProperty Parameters { get; set; }
#endif
        /// <summary>Array of scopes for the strategy.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.GitLab.OpenApiClient.Models.PutApiV4ProjectsIdFeatureFlagsFeatureFlagNameRequestStrategiesItemScopesItem>? Scopes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.GitLab.OpenApiClient.Models.PutApiV4ProjectsIdFeatureFlagsFeatureFlagNameRequestStrategiesItemScopesItem> Scopes { get; set; }
#endif
        /// <summary>ID of the feature flag user list. Applies only if the strategy is `gitlabUserList`.</summary>
        public int? UserListId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.PutApiV4ProjectsIdFeatureFlagsFeatureFlagNameRequestStrategiesItem"/> and sets the default values.
        /// </summary>
        public PutApiV4ProjectsIdFeatureFlagsFeatureFlagNameRequestStrategiesItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.PutApiV4ProjectsIdFeatureFlagsFeatureFlagNameRequestStrategiesItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.PutApiV4ProjectsIdFeatureFlagsFeatureFlagNameRequestStrategiesItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.PutApiV4ProjectsIdFeatureFlagsFeatureFlagNameRequestStrategiesItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "_destroy", n => { Destroy = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parameters", n => { Parameters = n.GetObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.PutApiV4ProjectsIdFeatureFlagsFeatureFlagNameRequestStrategiesItemParametersProperty>(global::Soenneker.GitLab.OpenApiClient.Models.PutApiV4ProjectsIdFeatureFlagsFeatureFlagNameRequestStrategiesItemParametersProperty.CreateFromDiscriminatorValue); } },
                { "scopes", n => { Scopes = n.GetCollectionOfObjectValues<global::Soenneker.GitLab.OpenApiClient.Models.PutApiV4ProjectsIdFeatureFlagsFeatureFlagNameRequestStrategiesItemScopesItem>(global::Soenneker.GitLab.OpenApiClient.Models.PutApiV4ProjectsIdFeatureFlagsFeatureFlagNameRequestStrategiesItemScopesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "user_list_id", n => { UserListId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("_destroy", Destroy);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.PutApiV4ProjectsIdFeatureFlagsFeatureFlagNameRequestStrategiesItemParametersProperty>("parameters", Parameters);
            writer.WriteCollectionOfObjectValues<global::Soenneker.GitLab.OpenApiClient.Models.PutApiV4ProjectsIdFeatureFlagsFeatureFlagNameRequestStrategiesItemScopesItem>("scopes", Scopes);
            writer.WriteIntValue("user_list_id", UserListId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
