// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>Subscription tier to rollout Elasticsearch for</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestBody5c6d6eacec15_plan
    {
        [EnumMember(Value = "bronze")]
        #pragma warning disable CS1591
        Bronze,
        #pragma warning restore CS1591
        [EnumMember(Value = "silver")]
        #pragma warning disable CS1591
        Silver,
        #pragma warning restore CS1591
        [EnumMember(Value = "premium")]
        #pragma warning disable CS1591
        Premium,
        #pragma warning restore CS1591
        [EnumMember(Value = "gold")]
        #pragma warning disable CS1591
        Gold,
        #pragma warning restore CS1591
        [EnumMember(Value = "ultimate")]
        #pragma warning disable CS1591
        Ultimate,
        #pragma warning restore CS1591
        [EnumMember(Value = "ultimate_trial")]
        #pragma warning disable CS1591
        Ultimate_trial,
        #pragma warning restore CS1591
        [EnumMember(Value = "ultimate_trial_paid_customer")]
        #pragma warning disable CS1591
        Ultimate_trial_paid_customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "premium_trial")]
        #pragma warning disable CS1591
        Premium_trial,
        #pragma warning restore CS1591
        [EnumMember(Value = "opensource")]
        #pragma warning disable CS1591
        Opensource,
        #pragma warning restore CS1591
    }
}
