// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RequestBodyB14B4C6Fd72E : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Create, edit, and delete custom agents and flows in the AI catalog.</summary>
        public bool? AdminAiCatalogItem { get; set; }
        /// <summary>Enable, disable, and configure custom agents and flows from the AI catalog for a project.</summary>
        public bool? AdminAiCatalogItemConsumer { get; set; }
        /// <summary>Create, read, update, and delete CI/CD variables.</summary>
        public bool? AdminCicdVariables { get; set; }
        /// <summary>Create, read, update, and delete compliance frameworks. Users with this permission can also assign a compliance framework label to a project, and set the default framework of a group.</summary>
        public bool? AdminComplianceFramework { get; set; }
        /// <summary>Add or remove users in a group, and assign roles to users. When assigning a role, users with this custom permission must select a role that has the same or fewer permissions as the default role used as the base for their custom role.</summary>
        public bool? AdminGroupMember { get; set; }
        /// <summary>Create, read, update, and delete integrations with external applications.</summary>
        public bool? AdminIntegrations { get; set; }
        /// <summary>Allows approval of merge requests.</summary>
        public bool? AdminMergeRequest { get; set; }
        /// <summary>Create, read, update, and delete protected branches for a project.</summary>
        public bool? AdminProtectedBranch { get; set; }
        /// <summary>Create, read, update, and delete protected environments</summary>
        public bool? AdminProtectedEnvironments { get; set; }
        /// <summary>Configure push rules for repositories at the group or project level.</summary>
        public bool? AdminPushRules { get; set; }
        /// <summary>Create, view, edit, and delete group or project Runners. Includes configuring Runner settings.</summary>
        public bool? AdminRunners { get; set; }
        /// <summary>Manage the security categories and attributes belonging to a top-level group. Also requires the `read_security_attribute` permission.</summary>
        public bool? AdminSecurityAttributes { get; set; }
        /// <summary>Execute terraform commands, lock/unlock terraform state files, and remove file versions.</summary>
        public bool? AdminTerraformState { get; set; }
        /// <summary>Edit the status, linked issue, and severity of a vulnerability object. Also requires the `read_vulnerability` permission.</summary>
        public bool? AdminVulnerability { get; set; }
        /// <summary>Manage webhooks</summary>
        public bool? AdminWebHook { get; set; }
        /// <summary>Apply security scan profiles.</summary>
        public bool? ApplySecurityScanProfiles { get; set; }
        /// <summary>Allows archiving of projects.</summary>
        public bool? ArchiveProject { get; set; }
        /// <summary>Base Access Level for the configured role</summary>
        public int? BaseAccessLevel { get; set; }
        /// <summary>Create security scan profiles.</summary>
        public bool? CreateSecurityScanProfiles { get; set; }
        /// <summary>Delete security scan profiles.</summary>
        public bool? DeleteSecurityScanProfiles { get; set; }
        /// <summary>Description for role</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Delete packages and package files in the package registry.</summary>
        public bool? DestroyPackage { get; set; }
        /// <summary>Manage deploy tokens at the group or project level.</summary>
        public bool? ManageDeployTokens { get; set; }
        /// <summary>Create, read, update, and delete group access tokens. When creating a token, users with this custom permission must select a role for that token that has the same or fewer permissions as the default role used as the base for the custom role.</summary>
        public bool? ManageGroupAccessTokens { get; set; }
        /// <summary>Configure merge request settings at the group or project level. Group actions include managing merge checks and approval settings. Project actions include managing MR configurations, approval rules and settings, and branch targets. In order to enable Suggested reviewers, the &quot;Manage project access tokens&quot; custom permission needs to be enabled.</summary>
        public bool? ManageMergeRequestSettings { get; set; }
        /// <summary>Create, read, update, and delete project access tokens. When creating a token, users with this custom permission must select a role for that token that has the same or fewer permissions as the default role used as the base for the custom role.</summary>
        public bool? ManageProjectAccessTokens { get; set; }
        /// <summary>Allows linking security policy projects.</summary>
        public bool? ManageSecurityPolicyLink { get; set; }
        /// <summary>Name for role (default: &apos;Custom&apos;)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Read CI/CD details for runners and jobs in the Admin Area.</summary>
        public bool? ReadAdminCicd { get; set; }
        /// <summary>Read group details in the Admin Area.</summary>
        public bool? ReadAdminGroups { get; set; }
        /// <summary>Read system information such as background migrations, health checks, and Gitaly in the Admin Area.</summary>
        public bool? ReadAdminMonitoring { get; set; }
        /// <summary>Read project details in the Admin Area.</summary>
        public bool? ReadAdminProjects { get; set; }
        /// <summary>Read subscription details in the Admin area.</summary>
        public bool? ReadAdminSubscription { get; set; }
        /// <summary>Read the user list and user details in the Admin area.</summary>
        public bool? ReadAdminUsers { get; set; }
        /// <summary>Read GitLab Duo Agent Platform artifacts, including audit events and session metadata, that are exposed through the agent artifacts dashboard.</summary>
        public bool? ReadAgentArtifacts { get; set; }
        /// <summary>Allows read-only access to the source code in the user interface. Does not allow users to edit or download repository archives, clone or pull repositories, view source code in an IDE, or view merge requests for private projects. You can download individual files because read-only access inherently grants the ability to make a local copy of the file.</summary>
        public bool? ReadCode { get; set; }
        /// <summary>Read compliance capabilities including adherence, violations, and frameworks for groups and projects.</summary>
        public bool? ReadComplianceDashboard { get; set; }
        /// <summary>Read CRM contact.</summary>
        public bool? ReadCrmContact { get; set; }
        /// <summary>Allows read-only access to the dependencies and licenses.</summary>
        public bool? ReadDependency { get; set; }
        /// <summary>Allows read-only access to group or project runners, including the runner fleet dashboard.</summary>
        public bool? ReadRunners { get; set; }
        /// <summary>Allows read-only access to the security categories and attributes that belong to a top-level group.</summary>
        public bool? ReadSecurityAttribute { get; set; }
        /// <summary>Read security scan profiles.</summary>
        public bool? ReadSecurityScanProfiles { get; set; }
        /// <summary>Allows read access to virtual registries at the group level. Enables users to resolve packages through the virtual registry without requiring broader group membership permissions. Only works on top level groups.</summary>
        public bool? ReadVirtualRegistry { get; set; }
        /// <summary>Read vulnerability reports and security dashboards.</summary>
        public bool? ReadVulnerability { get; set; }
        /// <summary>Ability to delete or restore a subgroup. This ability does not allow deleting top-level groups. Review the retention period settings to prevent accidental deletion.</summary>
        public bool? RemoveGroup { get; set; }
        /// <summary>Allows deletion of projects.</summary>
        public bool? RemoveProject { get; set; }
        /// <summary>Update security AI workflow settings such as SAST Vulnerability Resolution. Also requires the `read_vulnerability` permission.</summary>
        public bool? UpdateSecAiWorkflowSettings { get; set; }
        /// <summary>Update security scan profiles.</summary>
        public bool? UpdateSecurityScanProfiles { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyB14B4C6Fd72E"/> and sets the default values.
        /// </summary>
        public RequestBodyB14B4C6Fd72E()
        {
            AdditionalData = new Dictionary<string, object>();
            AdminAiCatalogItem = false;
            AdminAiCatalogItemConsumer = false;
            AdminCicdVariables = false;
            AdminComplianceFramework = false;
            AdminGroupMember = false;
            AdminIntegrations = false;
            AdminMergeRequest = false;
            AdminProtectedBranch = false;
            AdminProtectedEnvironments = false;
            AdminPushRules = false;
            AdminRunners = false;
            AdminSecurityAttributes = false;
            AdminTerraformState = false;
            AdminVulnerability = false;
            AdminWebHook = false;
            ApplySecurityScanProfiles = false;
            ArchiveProject = false;
            CreateSecurityScanProfiles = false;
            DeleteSecurityScanProfiles = false;
            DestroyPackage = false;
            ManageDeployTokens = false;
            ManageGroupAccessTokens = false;
            ManageMergeRequestSettings = false;
            ManageProjectAccessTokens = false;
            ManageSecurityPolicyLink = false;
            ReadAdminCicd = false;
            ReadAdminGroups = false;
            ReadAdminMonitoring = false;
            ReadAdminProjects = false;
            ReadAdminSubscription = false;
            ReadAdminUsers = false;
            ReadAgentArtifacts = false;
            ReadCode = false;
            ReadComplianceDashboard = false;
            ReadCrmContact = false;
            ReadDependency = false;
            ReadRunners = false;
            ReadSecurityAttribute = false;
            ReadSecurityScanProfiles = false;
            ReadVirtualRegistry = false;
            ReadVulnerability = false;
            RemoveGroup = false;
            RemoveProject = false;
            UpdateSecAiWorkflowSettings = false;
            UpdateSecurityScanProfiles = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyB14B4C6Fd72E"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyB14B4C6Fd72E CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyB14B4C6Fd72E();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "admin_ai_catalog_item", n => { AdminAiCatalogItem = n.GetBoolValue(); } },
                { "admin_ai_catalog_item_consumer", n => { AdminAiCatalogItemConsumer = n.GetBoolValue(); } },
                { "admin_cicd_variables", n => { AdminCicdVariables = n.GetBoolValue(); } },
                { "admin_compliance_framework", n => { AdminComplianceFramework = n.GetBoolValue(); } },
                { "admin_group_member", n => { AdminGroupMember = n.GetBoolValue(); } },
                { "admin_integrations", n => { AdminIntegrations = n.GetBoolValue(); } },
                { "admin_merge_request", n => { AdminMergeRequest = n.GetBoolValue(); } },
                { "admin_protected_branch", n => { AdminProtectedBranch = n.GetBoolValue(); } },
                { "admin_protected_environments", n => { AdminProtectedEnvironments = n.GetBoolValue(); } },
                { "admin_push_rules", n => { AdminPushRules = n.GetBoolValue(); } },
                { "admin_runners", n => { AdminRunners = n.GetBoolValue(); } },
                { "admin_security_attributes", n => { AdminSecurityAttributes = n.GetBoolValue(); } },
                { "admin_terraform_state", n => { AdminTerraformState = n.GetBoolValue(); } },
                { "admin_vulnerability", n => { AdminVulnerability = n.GetBoolValue(); } },
                { "admin_web_hook", n => { AdminWebHook = n.GetBoolValue(); } },
                { "apply_security_scan_profiles", n => { ApplySecurityScanProfiles = n.GetBoolValue(); } },
                { "archive_project", n => { ArchiveProject = n.GetBoolValue(); } },
                { "base_access_level", n => { BaseAccessLevel = n.GetIntValue(); } },
                { "create_security_scan_profiles", n => { CreateSecurityScanProfiles = n.GetBoolValue(); } },
                { "delete_security_scan_profiles", n => { DeleteSecurityScanProfiles = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "destroy_package", n => { DestroyPackage = n.GetBoolValue(); } },
                { "manage_deploy_tokens", n => { ManageDeployTokens = n.GetBoolValue(); } },
                { "manage_group_access_tokens", n => { ManageGroupAccessTokens = n.GetBoolValue(); } },
                { "manage_merge_request_settings", n => { ManageMergeRequestSettings = n.GetBoolValue(); } },
                { "manage_project_access_tokens", n => { ManageProjectAccessTokens = n.GetBoolValue(); } },
                { "manage_security_policy_link", n => { ManageSecurityPolicyLink = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "read_admin_cicd", n => { ReadAdminCicd = n.GetBoolValue(); } },
                { "read_admin_groups", n => { ReadAdminGroups = n.GetBoolValue(); } },
                { "read_admin_monitoring", n => { ReadAdminMonitoring = n.GetBoolValue(); } },
                { "read_admin_projects", n => { ReadAdminProjects = n.GetBoolValue(); } },
                { "read_admin_subscription", n => { ReadAdminSubscription = n.GetBoolValue(); } },
                { "read_admin_users", n => { ReadAdminUsers = n.GetBoolValue(); } },
                { "read_agent_artifacts", n => { ReadAgentArtifacts = n.GetBoolValue(); } },
                { "read_code", n => { ReadCode = n.GetBoolValue(); } },
                { "read_compliance_dashboard", n => { ReadComplianceDashboard = n.GetBoolValue(); } },
                { "read_crm_contact", n => { ReadCrmContact = n.GetBoolValue(); } },
                { "read_dependency", n => { ReadDependency = n.GetBoolValue(); } },
                { "read_runners", n => { ReadRunners = n.GetBoolValue(); } },
                { "read_security_attribute", n => { ReadSecurityAttribute = n.GetBoolValue(); } },
                { "read_security_scan_profiles", n => { ReadSecurityScanProfiles = n.GetBoolValue(); } },
                { "read_virtual_registry", n => { ReadVirtualRegistry = n.GetBoolValue(); } },
                { "read_vulnerability", n => { ReadVulnerability = n.GetBoolValue(); } },
                { "remove_group", n => { RemoveGroup = n.GetBoolValue(); } },
                { "remove_project", n => { RemoveProject = n.GetBoolValue(); } },
                { "update_sec_ai_workflow_settings", n => { UpdateSecAiWorkflowSettings = n.GetBoolValue(); } },
                { "update_security_scan_profiles", n => { UpdateSecurityScanProfiles = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("admin_ai_catalog_item", AdminAiCatalogItem);
            writer.WriteBoolValue("admin_ai_catalog_item_consumer", AdminAiCatalogItemConsumer);
            writer.WriteBoolValue("admin_cicd_variables", AdminCicdVariables);
            writer.WriteBoolValue("admin_compliance_framework", AdminComplianceFramework);
            writer.WriteBoolValue("admin_group_member", AdminGroupMember);
            writer.WriteBoolValue("admin_integrations", AdminIntegrations);
            writer.WriteBoolValue("admin_merge_request", AdminMergeRequest);
            writer.WriteBoolValue("admin_protected_branch", AdminProtectedBranch);
            writer.WriteBoolValue("admin_protected_environments", AdminProtectedEnvironments);
            writer.WriteBoolValue("admin_push_rules", AdminPushRules);
            writer.WriteBoolValue("admin_runners", AdminRunners);
            writer.WriteBoolValue("admin_security_attributes", AdminSecurityAttributes);
            writer.WriteBoolValue("admin_terraform_state", AdminTerraformState);
            writer.WriteBoolValue("admin_vulnerability", AdminVulnerability);
            writer.WriteBoolValue("admin_web_hook", AdminWebHook);
            writer.WriteBoolValue("apply_security_scan_profiles", ApplySecurityScanProfiles);
            writer.WriteBoolValue("archive_project", ArchiveProject);
            writer.WriteIntValue("base_access_level", BaseAccessLevel);
            writer.WriteBoolValue("create_security_scan_profiles", CreateSecurityScanProfiles);
            writer.WriteBoolValue("delete_security_scan_profiles", DeleteSecurityScanProfiles);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("destroy_package", DestroyPackage);
            writer.WriteBoolValue("manage_deploy_tokens", ManageDeployTokens);
            writer.WriteBoolValue("manage_group_access_tokens", ManageGroupAccessTokens);
            writer.WriteBoolValue("manage_merge_request_settings", ManageMergeRequestSettings);
            writer.WriteBoolValue("manage_project_access_tokens", ManageProjectAccessTokens);
            writer.WriteBoolValue("manage_security_policy_link", ManageSecurityPolicyLink);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("read_admin_cicd", ReadAdminCicd);
            writer.WriteBoolValue("read_admin_groups", ReadAdminGroups);
            writer.WriteBoolValue("read_admin_monitoring", ReadAdminMonitoring);
            writer.WriteBoolValue("read_admin_projects", ReadAdminProjects);
            writer.WriteBoolValue("read_admin_subscription", ReadAdminSubscription);
            writer.WriteBoolValue("read_admin_users", ReadAdminUsers);
            writer.WriteBoolValue("read_agent_artifacts", ReadAgentArtifacts);
            writer.WriteBoolValue("read_code", ReadCode);
            writer.WriteBoolValue("read_compliance_dashboard", ReadComplianceDashboard);
            writer.WriteBoolValue("read_crm_contact", ReadCrmContact);
            writer.WriteBoolValue("read_dependency", ReadDependency);
            writer.WriteBoolValue("read_runners", ReadRunners);
            writer.WriteBoolValue("read_security_attribute", ReadSecurityAttribute);
            writer.WriteBoolValue("read_security_scan_profiles", ReadSecurityScanProfiles);
            writer.WriteBoolValue("read_virtual_registry", ReadVirtualRegistry);
            writer.WriteBoolValue("read_vulnerability", ReadVulnerability);
            writer.WriteBoolValue("remove_group", RemoveGroup);
            writer.WriteBoolValue("remove_project", RemoveProject);
            writer.WriteBoolValue("update_sec_ai_workflow_settings", UpdateSecAiWorkflowSettings);
            writer.WriteBoolValue("update_security_scan_profiles", UpdateSecurityScanProfiles);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
