// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RequestBody3c400bb4e6e3 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Format of the generated report</summary>
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBody3c400bb4e6e3_export_format? ExportFormat { get; set; }
        /// <summary>An object that contains report components mapped to frontend data assets.Some report formats support embedding UI components from theUI. For example, users can apply certain filters in the web UI, andexport the component to a PDF. The SVG is provided fromthe frontend in the report data field.Unsupported keys are discarded. If the datadoesn&apos;t fit the component it is keyed to, thecomponent is ignored and an error is logged.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBody3c400bb4e6e3ReportData? ReportData { get; set; }
#nullable restore
#else
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBody3c400bb4e6e3ReportData ReportData { get; set; }
#endif
        /// <summary>The send_email property</summary>
        public bool? SendEmail { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBody3c400bb4e6e3"/> and sets the default values.
        /// </summary>
        public RequestBody3c400bb4e6e3()
        {
            AdditionalData = new Dictionary<string, object>();
            ExportFormat = global::Soenneker.GitLab.OpenApiClient.Models.RequestBody3c400bb4e6e3_export_format.Csv;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBody3c400bb4e6e3"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.RequestBody3c400bb4e6e3 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.RequestBody3c400bb4e6e3();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "export_format", n => { ExportFormat = n.GetEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody3c400bb4e6e3_export_format>(); } },
                { "report_data", n => { ReportData = n.GetObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody3c400bb4e6e3ReportData>(global::Soenneker.GitLab.OpenApiClient.Models.RequestBody3c400bb4e6e3ReportData.CreateFromDiscriminatorValue); } },
                { "send_email", n => { SendEmail = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody3c400bb4e6e3_export_format>("export_format", ExportFormat);
            writer.WriteObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody3c400bb4e6e3ReportData>("report_data", ReportData);
            writer.WriteBoolValue("send_email", SendEmail);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
