// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RequestBody_d2da9b0bcf29 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Minimum GitLab access level to allow to delete container images in the container registry.            For example maintainer, owner or admin.</summary>
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_d2da9b0bcf29_minimum_access_level_for_delete? MinimumAccessLevelForDelete { get; set; }
        /// <summary>Minimum GitLab access level to allow to push container images to the container registry.            For example maintainer, owner or admin.</summary>
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_d2da9b0bcf29_minimum_access_level_for_push? MinimumAccessLevelForPush { get; set; }
        /// <summary>Container repository path pattern protected by the protection rule.            For example `flight/flight-*`. Wildcard character `*` allowed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RepositoryPathPattern { get; set; }
#nullable restore
#else
        public string RepositoryPathPattern { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_d2da9b0bcf29"/> and sets the default values.
        /// </summary>
        public RequestBody_d2da9b0bcf29()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_d2da9b0bcf29"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_d2da9b0bcf29 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_d2da9b0bcf29();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "minimum_access_level_for_delete", n => { MinimumAccessLevelForDelete = n.GetEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_d2da9b0bcf29_minimum_access_level_for_delete>(); } },
                { "minimum_access_level_for_push", n => { MinimumAccessLevelForPush = n.GetEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_d2da9b0bcf29_minimum_access_level_for_push>(); } },
                { "repository_path_pattern", n => { RepositoryPathPattern = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_d2da9b0bcf29_minimum_access_level_for_delete>("minimum_access_level_for_delete", MinimumAccessLevelForDelete);
            writer.WriteEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_d2da9b0bcf29_minimum_access_level_for_push>("minimum_access_level_for_push", MinimumAccessLevelForPush);
            writer.WriteStringValue("repository_path_pattern", RepositoryPathPattern);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
