// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RequestBody9182400aa1f8 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Comma-separated label names to add to an issue</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AddLabels { get; set; }
#nullable restore
#else
        public List<string> AddLabels { get; set; }
#endif
        /// <summary>The color of an epic</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>Indicates if the epic is confidential</summary>
        public bool? Confidential { get; set; }
        /// <summary>The description of an epic</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The due date of an epic</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DueDateFixed { get; set; }
#nullable restore
#else
        public string DueDateFixed { get; set; }
#endif
        /// <summary>Indicates due date should be sourced from due_date_fixed field not the issue milestones</summary>
        public bool? DueDateIsFixed { get; set; }
        /// <summary>&quot;Deprecated: use due_date_fixed instead&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndDate { get; set; }
#nullable restore
#else
        public string EndDate { get; set; }
#endif
        /// <summary>Comma-separated label names for an issue</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Labels { get; set; }
#nullable restore
#else
        public List<string> Labels { get; set; }
#endif
        /// <summary>The ID of a parent epic</summary>
        public int? ParentId { get; set; }
        /// <summary>Comma-separated label names to remove from an issue</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RemoveLabels { get; set; }
#nullable restore
#else
        public List<string> RemoveLabels { get; set; }
#endif
        /// <summary>&quot;Deprecated: use start_date_fixed instead&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartDate { get; set; }
#nullable restore
#else
        public string StartDate { get; set; }
#endif
        /// <summary>The start date of an epic</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartDateFixed { get; set; }
#nullable restore
#else
        public string StartDateFixed { get; set; }
#endif
        /// <summary>Indicates start date should be sourced from start_date_fixed field not the issue milestones</summary>
        public bool? StartDateIsFixed { get; set; }
        /// <summary>State event for an epic</summary>
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBody9182400aa1f8_state_event? StateEvent { get; set; }
        /// <summary>The title of an epic</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Date time when the epic was updated. Available only for admins and project owners</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBody9182400aa1f8"/> and sets the default values.
        /// </summary>
        public RequestBody9182400aa1f8()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBody9182400aa1f8"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.RequestBody9182400aa1f8 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.RequestBody9182400aa1f8();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "add_labels", n => { AddLabels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "color", n => { Color = n.GetStringValue(); } },
                { "confidential", n => { Confidential = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "due_date_fixed", n => { DueDateFixed = n.GetStringValue(); } },
                { "due_date_is_fixed", n => { DueDateIsFixed = n.GetBoolValue(); } },
                { "end_date", n => { EndDate = n.GetStringValue(); } },
                { "labels", n => { Labels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "parent_id", n => { ParentId = n.GetIntValue(); } },
                { "remove_labels", n => { RemoveLabels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "start_date", n => { StartDate = n.GetStringValue(); } },
                { "start_date_fixed", n => { StartDateFixed = n.GetStringValue(); } },
                { "start_date_is_fixed", n => { StartDateIsFixed = n.GetBoolValue(); } },
                { "state_event", n => { StateEvent = n.GetEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody9182400aa1f8_state_event>(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("add_labels", AddLabels);
            writer.WriteStringValue("color", Color);
            writer.WriteBoolValue("confidential", Confidential);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("due_date_fixed", DueDateFixed);
            writer.WriteBoolValue("due_date_is_fixed", DueDateIsFixed);
            writer.WriteStringValue("end_date", EndDate);
            writer.WriteCollectionOfPrimitiveValues<string>("labels", Labels);
            writer.WriteIntValue("parent_id", ParentId);
            writer.WriteCollectionOfPrimitiveValues<string>("remove_labels", RemoveLabels);
            writer.WriteStringValue("start_date", StartDate);
            writer.WriteStringValue("start_date_fixed", StartDateFixed);
            writer.WriteBoolValue("start_date_is_fixed", StartDateIsFixed);
            writer.WriteEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody9182400aa1f8_state_event>("state_event", StateEvent);
            writer.WriteStringValue("title", Title);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
