// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>Where the session was triggered from</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestBody96013D8Cf931Source
    {
        [EnumMember(Value = "merge_request_code_conflict")]
        #pragma warning disable CS1591
        MergeRequestCodeConflict,
        #pragma warning restore CS1591
        [EnumMember(Value = "merge_request_dependency_bump")]
        #pragma warning disable CS1591
        MergeRequestDependencyBump,
        #pragma warning restore CS1591
        [EnumMember(Value = "merge_request_fix_pipeline")]
        #pragma warning disable CS1591
        MergeRequestFixPipeline,
        #pragma warning restore CS1591
        [EnumMember(Value = "merge_request_resolve_discussion")]
        #pragma warning disable CS1591
        MergeRequestResolveDiscussion,
        #pragma warning restore CS1591
        [EnumMember(Value = "work_item_to_merge_request")]
        #pragma warning disable CS1591
        WorkItemToMergeRequest,
        #pragma warning restore CS1591
        [EnumMember(Value = "fix_pipeline")]
        #pragma warning disable CS1591
        FixPipeline,
        #pragma warning restore CS1591
        [EnumMember(Value = "convert_platform_ci_pipeline")]
        #pragma warning disable CS1591
        ConvertPlatformCiPipeline,
        #pragma warning restore CS1591
    }
}
