// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>Broadcast type. Defaults to banner</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestBody78Bf83195133BroadcastType
    {
        [EnumMember(Value = "banner")]
        #pragma warning disable CS1591
        Banner,
        #pragma warning restore CS1591
        [EnumMember(Value = "notification")]
        #pragma warning disable CS1591
        Notification,
        #pragma warning restore CS1591
    }
}
