// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RequestBody1C287Db32396 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>&quot;Source restriction for write requests. Default: anywhere. Valid values: anywhere, ci_only, ci_on_protected_branch_only.&quot;</summary>
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBody1C287Db32396AllowedFrom? AllowedFrom { get; set; }
        /// <summary>&quot;Minimum GitLab access level required to write to the Terraform state. Valid values: developer, maintainer, owner, admin.&quot;</summary>
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBody1C287Db32396MinimumAccessLevelForWrite? MinimumAccessLevelForWrite { get; set; }
        /// <summary>Terraform state name to protect. Maximum 255 characters. Must be unique per project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StateName { get; set; }
#nullable restore
#else
        public string StateName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBody1C287Db32396"/> and sets the default values.
        /// </summary>
        public RequestBody1C287Db32396()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBody1C287Db32396"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.RequestBody1C287Db32396 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.RequestBody1C287Db32396();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowed_from", n => { AllowedFrom = n.GetEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody1C287Db32396AllowedFrom>(); } },
                { "minimum_access_level_for_write", n => { MinimumAccessLevelForWrite = n.GetEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody1C287Db32396MinimumAccessLevelForWrite>(); } },
                { "state_name", n => { StateName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody1C287Db32396AllowedFrom>("allowed_from", AllowedFrom);
            writer.WriteEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody1C287Db32396MinimumAccessLevelForWrite>("minimum_access_level_for_write", MinimumAccessLevelForWrite);
            writer.WriteStringValue("state_name", StateName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
