// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>State of the runner controller (disabled, enabled, dry_run)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestBody7951B0Aa051DState
    {
        [EnumMember(Value = "disabled")]
        #pragma warning disable CS1591
        Disabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "enabled")]
        #pragma warning disable CS1591
        Enabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "dry_run")]
        #pragma warning disable CS1591
        DryRun,
        #pragma warning restore CS1591
    }
}
