// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>The type of variable, must be one of env_var or file. Defaults to env_var</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestBody_16f5f03716b4_variables_variable_type
    {
        [EnumMember(Value = "env_var")]
        #pragma warning disable CS1591
        Env_var,
        #pragma warning restore CS1591
        [EnumMember(Value = "file")]
        #pragma warning disable CS1591
        File,
        #pragma warning restore CS1591
    }
}
