// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>Allow only the selected protocols to be used for Git access.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestBodyE83C2A25E7DaEnabledGitAccessProtocol
    {
        [EnumMember(Value = "ssh")]
        #pragma warning disable CS1591
        Ssh,
        #pragma warning restore CS1591
        [EnumMember(Value = "http")]
        #pragma warning disable CS1591
        Http,
        #pragma warning restore CS1591
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
    }
}
