// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>Format of the generated report</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestBody5306Ff1494D2ExportFormat
    {
        [EnumMember(Value = "csv")]
        #pragma warning disable CS1591
        Csv,
        #pragma warning restore CS1591
        [EnumMember(Value = "pdf")]
        #pragma warning disable CS1591
        Pdf,
        #pragma warning restore CS1591
    }
}
