// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RequestBody085de8932e54 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The access level of the runner</summary>
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBody085de8932e54_access_level? AccessLevel { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Description of the runner</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The ID of the group that the runner is created in</summary>
        public int? GroupId { get; set; }
        /// <summary>Specifies if the runner should be locked for the current project (defaults to false)</summary>
        public bool? Locked { get; set; }
        /// <summary>Free-form maintenance notes for the runner (1024 characters)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaintenanceNote { get; set; }
#nullable restore
#else
        public string MaintenanceNote { get; set; }
#endif
        /// <summary>Maximum timeout that limits the amount of time (in seconds) that runners can run jobs</summary>
        public int? MaximumTimeout { get; set; }
        /// <summary>Specifies if the runner should ignore new jobs (defaults to false)</summary>
        public bool? Paused { get; set; }
        /// <summary>The ID of the project that the runner is created in</summary>
        public int? ProjectId { get; set; }
        /// <summary>Specifies the scope of the runner</summary>
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBody085de8932e54_runner_type? RunnerType { get; set; }
        /// <summary>Specifies if the runner should handle untagged jobs  (defaults to true)</summary>
        public bool? RunUntagged { get; set; }
        /// <summary>A list of runner tags</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TagList { get; set; }
#nullable restore
#else
        public List<string> TagList { get; set; }
#endif
        /// <summary>The expiration time for the runner authentication token (ISO 8601 format). Must be between 5 minutes and 15 days in the future, and cannot exceed instance/group/project limits.</summary>
        public DateTimeOffset? TokenExpiresAt { get; set; }
        /// <summary>The deadline for token rotation (ISO 8601 format). Must be specified with token_expires_at and be &lt;= token_expires_at.</summary>
        public DateTimeOffset? TokenRotationDeadline { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBody085de8932e54"/> and sets the default values.
        /// </summary>
        public RequestBody085de8932e54()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBody085de8932e54"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.RequestBody085de8932e54 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.RequestBody085de8932e54();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access_level", n => { AccessLevel = n.GetEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody085de8932e54_access_level>(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "group_id", n => { GroupId = n.GetIntValue(); } },
                { "locked", n => { Locked = n.GetBoolValue(); } },
                { "maintenance_note", n => { MaintenanceNote = n.GetStringValue(); } },
                { "maximum_timeout", n => { MaximumTimeout = n.GetIntValue(); } },
                { "paused", n => { Paused = n.GetBoolValue(); } },
                { "project_id", n => { ProjectId = n.GetIntValue(); } },
                { "run_untagged", n => { RunUntagged = n.GetBoolValue(); } },
                { "runner_type", n => { RunnerType = n.GetEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody085de8932e54_runner_type>(); } },
                { "tag_list", n => { TagList = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "token_expires_at", n => { TokenExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "token_rotation_deadline", n => { TokenRotationDeadline = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody085de8932e54_access_level>("access_level", AccessLevel);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("group_id", GroupId);
            writer.WriteBoolValue("locked", Locked);
            writer.WriteStringValue("maintenance_note", MaintenanceNote);
            writer.WriteIntValue("maximum_timeout", MaximumTimeout);
            writer.WriteBoolValue("paused", Paused);
            writer.WriteIntValue("project_id", ProjectId);
            writer.WriteEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody085de8932e54_runner_type>("runner_type", RunnerType);
            writer.WriteBoolValue("run_untagged", RunUntagged);
            writer.WriteCollectionOfPrimitiveValues<string>("tag_list", TagList);
            writer.WriteDateTimeOffsetValue("token_expires_at", TokenExpiresAt);
            writer.WriteDateTimeOffsetValue("token_rotation_deadline", TokenRotationDeadline);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
