// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>The status of the deployment that is created. One of `running`, `success`, `failed`, or `canceled`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestBody_d170dfe7def6_status
    {
        [EnumMember(Value = "running")]
        #pragma warning disable CS1591
        Running,
        #pragma warning restore CS1591
        [EnumMember(Value = "success")]
        #pragma warning disable CS1591
        Success,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "canceled")]
        #pragma warning disable CS1591
        Canceled,
        #pragma warning restore CS1591
    }
}
