// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>Sets the behavior for Sidekiq job size limits. Default: &apos;compress&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestBody02F7C66B6A32SidekiqJobLimiterMode
    {
        [EnumMember(Value = "track")]
        #pragma warning disable CS1591
        Track,
        #pragma warning restore CS1591
        [EnumMember(Value = "compress")]
        #pragma warning disable CS1591
        Compress,
        #pragma warning restore CS1591
    }
}
