// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>Prompt injection protection level. One of `no_checks`, `log_only` or `interrupt`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestBodyE83C2A25E7DaAiSettingsAttributesPromptInjectionProtectionLevel
    {
        [EnumMember(Value = "no_checks")]
        #pragma warning disable CS1591
        NoChecks,
        #pragma warning restore CS1591
        [EnumMember(Value = "log_only")]
        #pragma warning disable CS1591
        LogOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "interrupt")]
        #pragma warning disable CS1591
        Interrupt,
        #pragma warning restore CS1591
    }
}
