// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RequestBodyD37b666c4842 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Runner&apos;s metadata</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyD37b666c4842Info? Info { get; set; }
#nullable restore
#else
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyD37b666c4842Info Info { get; set; }
#endif
        /// <summary>Runner&apos;s queue last_update token</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastUpdate { get; set; }
#nullable restore
#else
        public string LastUpdate { get; set; }
#endif
        /// <summary>Runner&apos;s session data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyD37b666c4842Session? Session { get; set; }
#nullable restore
#else
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyD37b666c4842Session Session { get; set; }
#endif
        /// <summary>Runner&apos;s system identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SystemId { get; set; }
#nullable restore
#else
        public string SystemId { get; set; }
#endif
        /// <summary>Runner&apos;s authentication token</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Token { get; set; }
#nullable restore
#else
        public string Token { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyD37b666c4842"/> and sets the default values.
        /// </summary>
        public RequestBodyD37b666c4842()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyD37b666c4842"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyD37b666c4842 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyD37b666c4842();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "info", n => { Info = n.GetObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyD37b666c4842Info>(global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyD37b666c4842Info.CreateFromDiscriminatorValue); } },
                { "last_update", n => { LastUpdate = n.GetStringValue(); } },
                { "session", n => { Session = n.GetObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyD37b666c4842Session>(global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyD37b666c4842Session.CreateFromDiscriminatorValue); } },
                { "system_id", n => { SystemId = n.GetStringValue(); } },
                { "token", n => { Token = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyD37b666c4842Info>("info", Info);
            writer.WriteStringValue("last_update", LastUpdate);
            writer.WriteObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyD37b666c4842Session>("session", Session);
            writer.WriteStringValue("system_id", SystemId);
            writer.WriteStringValue("token", Token);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
