// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>Scope of usage for the SSH key</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestBodyDaa524573b36_usage_type
    {
        [EnumMember(Value = "auth_and_signing")]
        #pragma warning disable CS1591
        Auth_and_signing,
        #pragma warning restore CS1591
        [EnumMember(Value = "auth")]
        #pragma warning disable CS1591
        Auth,
        #pragma warning restore CS1591
        [EnumMember(Value = "signing")]
        #pragma warning disable CS1591
        Signing,
        #pragma warning restore CS1591
    }
}
