// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RequestBody400Cbb8B1B3A : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>If `true`, enables fast mode for dependency path graph builds, recording one path per dependency instead of all possible paths to reduce memory and processing time for large dependency graphs. Requires the `dependency_paths` feature flag to be enabled. At least one of `secret_push_protection_enabled`, `pre_receive_secret_detection_enabled`, `fast_dependency_paths_enabled` must be provided.</summary>
        public bool? FastDependencyPathsEnabled { get; set; }
        /// <summary>If `true`, enables secret push protection for the project. [Deprecated](https://gitlab.com/gitlab-org/gitlab/-/issues/514413) in GitLab 17.9. Use `secret_push_protection_enabled` instead. At least one of `secret_push_protection_enabled`, `pre_receive_secret_detection_enabled`, `fast_dependency_paths_enabled` must be provided.</summary>
        public bool? PreReceiveSecretDetectionEnabled { get; set; }
        /// <summary>If `true`, enables secret push protection for the project. At least one of `secret_push_protection_enabled`, `pre_receive_secret_detection_enabled`, `fast_dependency_paths_enabled` must be provided.</summary>
        public bool? SecretPushProtectionEnabled { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBody400Cbb8B1B3A"/> and sets the default values.
        /// </summary>
        public RequestBody400Cbb8B1B3A()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBody400Cbb8B1B3A"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.RequestBody400Cbb8B1B3A CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.RequestBody400Cbb8B1B3A();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "fast_dependency_paths_enabled", n => { FastDependencyPathsEnabled = n.GetBoolValue(); } },
                { "pre_receive_secret_detection_enabled", n => { PreReceiveSecretDetectionEnabled = n.GetBoolValue(); } },
                { "secret_push_protection_enabled", n => { SecretPushProtectionEnabled = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("fast_dependency_paths_enabled", FastDependencyPathsEnabled);
            writer.WriteBoolValue("pre_receive_secret_detection_enabled", PreReceiveSecretDetectionEnabled);
            writer.WriteBoolValue("secret_push_protection_enabled", SecretPushProtectionEnabled);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
