// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>Cluster authorization type, defaults to RBAC</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestBody6Db444F61Ca6PlatformKubernetesAttributesAuthorizationType
    {
        [EnumMember(Value = "unknown_authorization")]
        #pragma warning disable CS1591
        UnknownAuthorization,
        #pragma warning restore CS1591
        [EnumMember(Value = "rbac")]
        #pragma warning disable CS1591
        Rbac,
        #pragma warning restore CS1591
        [EnumMember(Value = "abac")]
        #pragma warning disable CS1591
        Abac,
        #pragma warning restore CS1591
    }
}
