// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>Rollout strategy for a percentage `value`. Omit it to apply the percentage to time. Mutually exclusive with `feature_group`, `user`, `group`, `namespace`, `project`, `organization`, `repository`, `runner`, `endpoint`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestBody198Bcb5C2AbfKey
    {
        [EnumMember(Value = "percentage_of_actors")]
        #pragma warning disable CS1591
        PercentageOfActors,
        #pragma warning restore CS1591
        [EnumMember(Value = "percentage_of_time")]
        #pragma warning disable CS1591
        PercentageOfTime,
        #pragma warning restore CS1591
    }
}
