// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>File format of the export</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestBody5a2db215793f_export_type
    {
        [EnumMember(Value = ":dependency_list")]
        #pragma warning disable CS1591
        Dependency_list,
        #pragma warning restore CS1591
        [EnumMember(Value = ":csv")]
        #pragma warning disable CS1591
        Csv,
        #pragma warning restore CS1591
        [EnumMember(Value = ":cyclonedx_1_6_json")]
        #pragma warning disable CS1591
        Cyclonedx_1_6_json,
        #pragma warning restore CS1591
    }
}
