// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>The type of the link: `other`, `runbook`, `image`, or `package`. Defaults to `other`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestBody1Ad2027Fd370LinkType
    {
        [EnumMember(Value = "other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
        [EnumMember(Value = "runbook")]
        #pragma warning disable CS1591
        Runbook,
        #pragma warning restore CS1591
        [EnumMember(Value = "image")]
        #pragma warning disable CS1591
        Image,
        #pragma warning restore CS1591
        [EnumMember(Value = "package")]
        #pragma warning disable CS1591
        Package,
        #pragma warning restore CS1591
    }
}
