// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyA8cab86e12aeBlockingProjectId_Branch1"/>, <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyA8cab86e12aeBlockingProjectId_Branch2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RequestBodyA8cab86e12aeBlockingProjectId : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyA8cab86e12aeBlockingProjectId_Branch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyA8cab86e12aeBlockingProjectId_Branch1? RequestBodyA8cab86e12aeBlockingProjectIdBranch1 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyA8cab86e12aeBlockingProjectId_Branch1 RequestBodyA8cab86e12aeBlockingProjectIdBranch1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyA8cab86e12aeBlockingProjectId_Branch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyA8cab86e12aeBlockingProjectId_Branch2? RequestBodyA8cab86e12aeBlockingProjectIdBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyA8cab86e12aeBlockingProjectId_Branch2 RequestBodyA8cab86e12aeBlockingProjectIdBranch2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyA8cab86e12aeBlockingProjectId"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyA8cab86e12aeBlockingProjectId CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyA8cab86e12aeBlockingProjectId();
            if("RequestBodyA8cab86e12aeBlockingProjectId_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.RequestBodyA8cab86e12aeBlockingProjectIdBranch1 = new global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyA8cab86e12aeBlockingProjectId_Branch1();
            }
            else if("RequestBodyA8cab86e12aeBlockingProjectId_2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.RequestBodyA8cab86e12aeBlockingProjectIdBranch2 = new global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyA8cab86e12aeBlockingProjectId_Branch2();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(RequestBodyA8cab86e12aeBlockingProjectIdBranch1 != null)
            {
                return RequestBodyA8cab86e12aeBlockingProjectIdBranch1.GetFieldDeserializers();
            }
            else if(RequestBodyA8cab86e12aeBlockingProjectIdBranch2 != null)
            {
                return RequestBodyA8cab86e12aeBlockingProjectIdBranch2.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(RequestBodyA8cab86e12aeBlockingProjectIdBranch1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyA8cab86e12aeBlockingProjectId_Branch1>(null, RequestBodyA8cab86e12aeBlockingProjectIdBranch1);
            }
            else if(RequestBodyA8cab86e12aeBlockingProjectIdBranch2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyA8cab86e12aeBlockingProjectId_Branch2>(null, RequestBodyA8cab86e12aeBlockingProjectIdBranch2);
            }
        }
    }
}
#pragma warning restore CS0618
