// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>The theme for the message</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestBody_334c625847ee_theme
    {
        [EnumMember(Value = "indigo")]
        #pragma warning disable CS1591
        Indigo,
        #pragma warning restore CS1591
        [EnumMember(Value = "light-indigo")]
        #pragma warning disable CS1591
        LightIndigo,
        #pragma warning restore CS1591
        [EnumMember(Value = "blue")]
        #pragma warning disable CS1591
        Blue,
        #pragma warning restore CS1591
        [EnumMember(Value = "light-blue")]
        #pragma warning disable CS1591
        LightBlue,
        #pragma warning restore CS1591
        [EnumMember(Value = "green")]
        #pragma warning disable CS1591
        Green,
        #pragma warning restore CS1591
        [EnumMember(Value = "light-green")]
        #pragma warning disable CS1591
        LightGreen,
        #pragma warning restore CS1591
        [EnumMember(Value = "red")]
        #pragma warning disable CS1591
        Red,
        #pragma warning restore CS1591
        [EnumMember(Value = "light-red")]
        #pragma warning disable CS1591
        LightRed,
        #pragma warning restore CS1591
        [EnumMember(Value = "dark")]
        #pragma warning disable CS1591
        Dark,
        #pragma warning restore CS1591
        [EnumMember(Value = "light")]
        #pragma warning disable CS1591
        Light,
        #pragma warning restore CS1591
    }
}
