// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>&quot;The type of the link: `other`, `runbook`, `image`, or `package`. Defaults to `other`&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestBody_3609c40a5e04_link_type
    {
        [EnumMember(Value = "other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
        [EnumMember(Value = "runbook")]
        #pragma warning disable CS1591
        Runbook,
        #pragma warning restore CS1591
        [EnumMember(Value = "image")]
        #pragma warning disable CS1591
        Image,
        #pragma warning restore CS1591
        [EnumMember(Value = "package")]
        #pragma warning disable CS1591
        Package,
        #pragma warning restore CS1591
    }
}
