// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RequestBody_895e747bc5d3 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? Approver { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? ChangeReviewerMergeRequest { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? CloseIssue { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? CloseMergeRequest { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? FailedPipeline { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? FixedPipeline { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? IssueDue { get; set; }
        /// <summary>The global notification level</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level { get; set; }
#nullable restore
#else
        public string Level { get; set; }
#endif
        /// <summary>Enable/disable this notification</summary>
        public bool? MergeMergeRequest { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? MergeWhenPipelineSucceeds { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? MovedProject { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? NewEpic { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? NewIssue { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? NewMergeRequest { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? NewNote { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? NewRelease { get; set; }
        /// <summary>The email address to send notifications</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NotificationEmail { get; set; }
#nullable restore
#else
        public string NotificationEmail { get; set; }
#endif
        /// <summary>Enable/disable this notification</summary>
        public bool? PushToMergeRequest { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? ReassignIssue { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? ReassignMergeRequest { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? ReopenIssue { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? ReopenMergeRequest { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? ServiceAccountFailedPipeline { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? ServiceAccountFixedPipeline { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? ServiceAccountSuccessPipeline { get; set; }
        /// <summary>Enable/disable this notification</summary>
        public bool? SuccessPipeline { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_895e747bc5d3"/> and sets the default values.
        /// </summary>
        public RequestBody_895e747bc5d3()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_895e747bc5d3"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_895e747bc5d3 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_895e747bc5d3();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "approver", n => { Approver = n.GetBoolValue(); } },
                { "change_reviewer_merge_request", n => { ChangeReviewerMergeRequest = n.GetBoolValue(); } },
                { "close_issue", n => { CloseIssue = n.GetBoolValue(); } },
                { "close_merge_request", n => { CloseMergeRequest = n.GetBoolValue(); } },
                { "failed_pipeline", n => { FailedPipeline = n.GetBoolValue(); } },
                { "fixed_pipeline", n => { FixedPipeline = n.GetBoolValue(); } },
                { "issue_due", n => { IssueDue = n.GetBoolValue(); } },
                { "level", n => { Level = n.GetStringValue(); } },
                { "merge_merge_request", n => { MergeMergeRequest = n.GetBoolValue(); } },
                { "merge_when_pipeline_succeeds", n => { MergeWhenPipelineSucceeds = n.GetBoolValue(); } },
                { "moved_project", n => { MovedProject = n.GetBoolValue(); } },
                { "new_epic", n => { NewEpic = n.GetBoolValue(); } },
                { "new_issue", n => { NewIssue = n.GetBoolValue(); } },
                { "new_merge_request", n => { NewMergeRequest = n.GetBoolValue(); } },
                { "new_note", n => { NewNote = n.GetBoolValue(); } },
                { "new_release", n => { NewRelease = n.GetBoolValue(); } },
                { "notification_email", n => { NotificationEmail = n.GetStringValue(); } },
                { "push_to_merge_request", n => { PushToMergeRequest = n.GetBoolValue(); } },
                { "reassign_issue", n => { ReassignIssue = n.GetBoolValue(); } },
                { "reassign_merge_request", n => { ReassignMergeRequest = n.GetBoolValue(); } },
                { "reopen_issue", n => { ReopenIssue = n.GetBoolValue(); } },
                { "reopen_merge_request", n => { ReopenMergeRequest = n.GetBoolValue(); } },
                { "service_account_failed_pipeline", n => { ServiceAccountFailedPipeline = n.GetBoolValue(); } },
                { "service_account_fixed_pipeline", n => { ServiceAccountFixedPipeline = n.GetBoolValue(); } },
                { "service_account_success_pipeline", n => { ServiceAccountSuccessPipeline = n.GetBoolValue(); } },
                { "success_pipeline", n => { SuccessPipeline = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("approver", Approver);
            writer.WriteBoolValue("change_reviewer_merge_request", ChangeReviewerMergeRequest);
            writer.WriteBoolValue("close_issue", CloseIssue);
            writer.WriteBoolValue("close_merge_request", CloseMergeRequest);
            writer.WriteBoolValue("failed_pipeline", FailedPipeline);
            writer.WriteBoolValue("fixed_pipeline", FixedPipeline);
            writer.WriteBoolValue("issue_due", IssueDue);
            writer.WriteStringValue("level", Level);
            writer.WriteBoolValue("merge_merge_request", MergeMergeRequest);
            writer.WriteBoolValue("merge_when_pipeline_succeeds", MergeWhenPipelineSucceeds);
            writer.WriteBoolValue("moved_project", MovedProject);
            writer.WriteBoolValue("new_epic", NewEpic);
            writer.WriteBoolValue("new_issue", NewIssue);
            writer.WriteBoolValue("new_merge_request", NewMergeRequest);
            writer.WriteBoolValue("new_note", NewNote);
            writer.WriteBoolValue("new_release", NewRelease);
            writer.WriteStringValue("notification_email", NotificationEmail);
            writer.WriteBoolValue("push_to_merge_request", PushToMergeRequest);
            writer.WriteBoolValue("reassign_issue", ReassignIssue);
            writer.WriteBoolValue("reassign_merge_request", ReassignMergeRequest);
            writer.WriteBoolValue("reopen_issue", ReopenIssue);
            writer.WriteBoolValue("reopen_merge_request", ReopenMergeRequest);
            writer.WriteBoolValue("service_account_failed_pipeline", ServiceAccountFailedPipeline);
            writer.WriteBoolValue("service_account_fixed_pipeline", ServiceAccountFixedPipeline);
            writer.WriteBoolValue("service_account_success_pipeline", ServiceAccountSuccessPipeline);
            writer.WriteBoolValue("success_pipeline", SuccessPipeline);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
