// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    /// <summary>Determines the mirror authentication method</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestBody_85deefe82a07_auth_method
    {
        [EnumMember(Value = "ssh_public_key")]
        #pragma warning disable CS1591
        Ssh_public_key,
        #pragma warning restore CS1591
        [EnumMember(Value = "password")]
        #pragma warning disable CS1591
        Password,
        #pragma warning restore CS1591
    }
}
