// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RequestBody_0d4da68f991a : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Comma-separated list of label names</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AddLabels { get; set; }
#nullable restore
#else
        public List<string> AddLabels { get; set; }
#endif
        /// <summary>[Deprecated] The ID of a user to assign issue</summary>
        public int? AssigneeId { get; set; }
        /// <summary>The array of user IDs to assign issue</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? AssigneeIds { get; set; }
#nullable restore
#else
        public List<int?> AssigneeIds { get; set; }
#endif
        /// <summary>Boolean parameter if the issue should be confidential</summary>
        public bool? Confidential { get; set; }
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The description of an issue</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary> Boolean parameter indicating if the issue&apos;s discussion is locked</summary>
        public bool? DiscussionLocked { get; set; }
        /// <summary>Date string in the format YEAR-MONTH-DAY</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DueDate { get; set; }
#nullable restore
#else
        public string DueDate { get; set; }
#endif
        /// <summary>The ID of an epic to associate the issue with</summary>
        public int? EpicId { get; set; }
        /// <summary>The IID of an epic to associate the issue with (deprecated)</summary>
        public int? EpicIid { get; set; }
        /// <summary>&quot;The type of the issue. Accepts: issue, incident, test_case, requirement, task, ticket&quot;</summary>
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_0d4da68f991a_issue_type? IssueType { get; set; }
        /// <summary>Comma-separated list of label names</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Labels { get; set; }
#nullable restore
#else
        public List<string> Labels { get; set; }
#endif
        /// <summary>The ID of a milestone to assign issue</summary>
        public int? MilestoneId { get; set; }
        /// <summary>Comma-separated list of label names</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RemoveLabels { get; set; }
#nullable restore
#else
        public List<string> RemoveLabels { get; set; }
#endif
        /// <summary>State of the issue</summary>
        public global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_0d4da68f991a_state_event? StateEvent { get; set; }
        /// <summary>The title of an issue</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Date time when the issue was updated. Available only for admins and project owners.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The weight of the issue</summary>
        public int? Weight { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_0d4da68f991a"/> and sets the default values.
        /// </summary>
        public RequestBody_0d4da68f991a()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_0d4da68f991a"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_0d4da68f991a CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_0d4da68f991a();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "add_labels", n => { AddLabels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "assignee_id", n => { AssigneeId = n.GetIntValue(); } },
                { "assignee_ids", n => { AssigneeIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "confidential", n => { Confidential = n.GetBoolValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "discussion_locked", n => { DiscussionLocked = n.GetBoolValue(); } },
                { "due_date", n => { DueDate = n.GetStringValue(); } },
                { "epic_id", n => { EpicId = n.GetIntValue(); } },
                { "epic_iid", n => { EpicIid = n.GetIntValue(); } },
                { "issue_type", n => { IssueType = n.GetEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_0d4da68f991a_issue_type>(); } },
                { "labels", n => { Labels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "milestone_id", n => { MilestoneId = n.GetIntValue(); } },
                { "remove_labels", n => { RemoveLabels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "state_event", n => { StateEvent = n.GetEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_0d4da68f991a_state_event>(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "weight", n => { Weight = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("add_labels", AddLabels);
            writer.WriteIntValue("assignee_id", AssigneeId);
            writer.WriteCollectionOfPrimitiveValues<int?>("assignee_ids", AssigneeIds);
            writer.WriteBoolValue("confidential", Confidential);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("discussion_locked", DiscussionLocked);
            writer.WriteStringValue("due_date", DueDate);
            writer.WriteIntValue("epic_id", EpicId);
            writer.WriteIntValue("epic_iid", EpicIid);
            writer.WriteEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_0d4da68f991a_issue_type>("issue_type", IssueType);
            writer.WriteCollectionOfPrimitiveValues<string>("labels", Labels);
            writer.WriteIntValue("milestone_id", MilestoneId);
            writer.WriteCollectionOfPrimitiveValues<string>("remove_labels", RemoveLabels);
            writer.WriteEnumValue<global::Soenneker.GitLab.OpenApiClient.Models.RequestBody_0d4da68f991a_state_event>("state_event", StateEvent);
            writer.WriteStringValue("title", Title);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteIntValue("weight", Weight);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
