// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.GitLab.OpenApiClient.Api.V4.Projects.Item.Packages.Ml_models.Item.Files;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.GitLab.OpenApiClient.Api.V4.Projects.Item.Packages.Ml_models.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\projects\{-id}\packages\ml_models\{modelVersionId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithModelVersionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The files property</summary>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.Projects.Item.Packages.Ml_models.Item.Files.FilesRequestBuilder Files
        {
            get => new global::Soenneker.GitLab.OpenApiClient.Api.V4.Projects.Item.Packages.Ml_models.Item.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Projects.Item.Packages.Ml_models.Item.WithModelVersionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithModelVersionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/projects/{%2Did}/packages/ml_models/{modelVersionId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Projects.Item.Packages.Ml_models.Item.WithModelVersionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithModelVersionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/projects/{%2Did}/packages/ml_models/{modelVersionId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
