// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Packages
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetStatusQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "default")]
        #pragma warning disable CS1591
        Default,
        #pragma warning restore CS1591
        [EnumMember(Value = "hidden")]
        #pragma warning disable CS1591
        Hidden,
        #pragma warning restore CS1591
        [EnumMember(Value = "processing")]
        #pragma warning disable CS1591
        Processing,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending_destruction")]
        #pragma warning disable CS1591
        Pending_destruction,
        #pragma warning restore CS1591
        [EnumMember(Value = "deprecated")]
        #pragma warning disable CS1591
        Deprecated,
        #pragma warning restore CS1591
    }
}
