// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\internal\agents\agentw\authorize_user_access
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Authorize_user_accessRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access.Authorize_user_accessRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Authorize_user_accessRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/internal/agents/agentw/authorize_user_access?user_id={user_id}&workspace_host={workspace_host}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access.Authorize_user_accessRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Authorize_user_accessRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/internal/agents/agentw/authorize_user_access?user_id={user_id}&workspace_host={workspace_host}", rawUrl)
        {
        }
        /// <summary>
        /// Returns whether the user is authorized to access the workspace.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access.Authorize_user_accessGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access.Authorize_user_accessGetResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access.Authorize_user_accessRequestBuilder.Authorize_user_accessRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access.Authorize_user_accessGetResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access.Authorize_user_accessRequestBuilder.Authorize_user_accessRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access.Authorize_user_accessGetResponse>(requestInfo, global::Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access.Authorize_user_accessGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns whether the user is authorized to access the workspace.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access.Authorize_user_accessRequestBuilder.Authorize_user_accessRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access.Authorize_user_accessRequestBuilder.Authorize_user_accessRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access.Authorize_user_accessRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access.Authorize_user_accessRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access.Authorize_user_accessRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns whether the user is authorized to access the workspace.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Authorize_user_accessRequestBuilderGetQueryParameters 
        {
            /// <summary>User ID of the user accessing the workspace</summary>
            [QueryParameter("user_id")]
            public int? UserId { get; set; }
            /// <summary>Host of the workspace being accessed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("workspace_host")]
            public string? WorkspaceHost { get; set; }
#nullable restore
#else
            [QueryParameter("workspace_host")]
            public string WorkspaceHost { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
