// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access
{
    /// <summary>
    /// Default response schema
    /// </summary>
    [Obsolete("This class is obsolete. Use Authorize_user_accessGetResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Authorize_user_accessResponse : global::Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access.Authorize_user_accessGetResponse, IParsable
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access.Authorize_user_accessResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access.Authorize_user_accessResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.GitLab.OpenApiClient.Api.V4.Internal.Agents.Agentw.Authorize_user_access.Authorize_user_accessResponse();
        }
    }
}
#pragma warning restore CS0618
