// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.GitLab.OpenApiClient.Api.V4.Todos.Item.Mark_as_done;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.GitLab.OpenApiClient.Api.V4.Todos.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\todos\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TodosItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The mark_as_done property</summary>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.Todos.Item.Mark_as_done.Mark_as_doneRequestBuilder Mark_as_done
        {
            get => new global::Soenneker.GitLab.OpenApiClient.Api.V4.Todos.Item.Mark_as_done.Mark_as_doneRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Todos.Item.TodosItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TodosItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/todos/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Todos.Item.TodosItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TodosItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/todos/{id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
