// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.GitLab.OpenApiClient.Api.V4.User.Activities;
using Soenneker.GitLab.OpenApiClient.Api.V4.User.Avatar;
using Soenneker.GitLab.OpenApiClient.Api.V4.User.Emails;
using Soenneker.GitLab.OpenApiClient.Api.V4.User.Gpg_keys;
using Soenneker.GitLab.OpenApiClient.Api.V4.User.Keys;
using Soenneker.GitLab.OpenApiClient.Api.V4.User.Personal_access_tokens;
using Soenneker.GitLab.OpenApiClient.Api.V4.User.Preferences;
using Soenneker.GitLab.OpenApiClient.Api.V4.User.Runners;
using Soenneker.GitLab.OpenApiClient.Api.V4.User.Status;
using Soenneker.GitLab.OpenApiClient.Api.V4.User.Support_pin;
using Soenneker.GitLab.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.GitLab.OpenApiClient.Api.V4.User
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\user
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The activities property</summary>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Activities.ActivitiesRequestBuilder Activities
        {
            get => new global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Activities.ActivitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The avatar property</summary>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Avatar.AvatarRequestBuilder Avatar
        {
            get => new global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Avatar.AvatarRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The emails property</summary>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Emails.EmailsRequestBuilder Emails
        {
            get => new global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Emails.EmailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The gpg_keys property</summary>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Gpg_keys.Gpg_keysRequestBuilder Gpg_keys
        {
            get => new global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Gpg_keys.Gpg_keysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The keys property</summary>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Keys.KeysRequestBuilder Keys
        {
            get => new global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Keys.KeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The personal_access_tokens property</summary>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Personal_access_tokens.Personal_access_tokensRequestBuilder Personal_access_tokens
        {
            get => new global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Personal_access_tokens.Personal_access_tokensRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The preferences property</summary>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Preferences.PreferencesRequestBuilder Preferences
        {
            get => new global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Preferences.PreferencesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The runners property</summary>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Runners.RunnersRequestBuilder Runners
        {
            get => new global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Runners.RunnersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Status.StatusRequestBuilder Status
        {
            get => new global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The support_pin property</summary>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Support_pin.Support_pinRequestBuilder Support_pin
        {
            get => new global::Soenneker.GitLab.OpenApiClient.Api.V4.User.Support_pin.Support_pinRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/user", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/user", rawUrl)
        {
        }
        /// <summary>
        /// Get the currently authenticated user
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesUserPublic"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesUserPublic?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesUserPublic> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesUserPublic>(requestInfo, global::Soenneker.GitLab.OpenApiClient.Models.APIEntitiesUserPublic.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the currently authenticated user
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.User.UserRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.User.UserRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.GitLab.OpenApiClient.Api.V4.User.UserRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
