// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Api.V4.Databases.Item.Dictionary.Tables
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetTable_sizeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "small")]
        #pragma warning disable CS1591
        Small,
        #pragma warning restore CS1591
        [EnumMember(Value = "medium")]
        #pragma warning disable CS1591
        Medium,
        #pragma warning restore CS1591
        [EnumMember(Value = "large")]
        #pragma warning disable CS1591
        Large,
        #pragma warning restore CS1591
        [EnumMember(Value = "over_limit")]
        #pragma warning disable CS1591
        Over_limit,
        #pragma warning restore CS1591
    }
}
