// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.GitLab.OpenApiClient.Api.V4.Packages.Terraform.Modules.V1.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.GitLab.OpenApiClient.Api.V4.Packages.Terraform.Modules.V1.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\packages\terraform\modules\v1\{module_namespace}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithModule_namespaceItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.GitLab.OpenApiClient.api.v4.packages.terraform.modules.v1.item.item collection</summary>
        /// <param name="position">Name of the module</param>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Packages.Terraform.Modules.V1.Item.Item.WithModule_nameItemRequestBuilder"/></returns>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.Packages.Terraform.Modules.V1.Item.Item.WithModule_nameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("module_name", position);
                return new global::Soenneker.GitLab.OpenApiClient.Api.V4.Packages.Terraform.Modules.V1.Item.Item.WithModule_nameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Packages.Terraform.Modules.V1.Item.WithModule_namespaceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithModule_namespaceItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/packages/terraform/modules/v1/{module_namespace}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Packages.Terraform.Modules.V1.Item.WithModule_namespaceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithModule_namespaceItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/packages/terraform/modules/v1/{module_namespace}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
