// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.GitLab.OpenApiClient.Api.V4.Pipelines.Item;
using Soenneker.GitLab.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.GitLab.OpenApiClient.Api.V4.Pipelines
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\pipelines
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PipelinesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.GitLab.OpenApiClient.api.v4.pipelines.item collection</summary>
        /// <param name="position">The ID of the pipeline</param>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Pipelines.Item.PipelinesItemRequestBuilder"/></returns>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.Pipelines.Item.PipelinesItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.GitLab.OpenApiClient.Api.V4.Pipelines.Item.PipelinesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Pipelines.PipelinesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PipelinesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/pipelines{?created_after*,created_before*,cursor*,order_by*,per_page*,sort*,source*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Pipelines.PipelinesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PipelinesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/pipelines{?created_after*,created_before*,cursor*,order_by*,per_page*,sort*,source*}", rawUrl)
        {
        }
        /// <summary>
        /// Lists recently created pipelines across all projects that were triggered by the authenticated user. By default, child pipelines are not included in the results. To return child pipelines, set `source` to `parent_pipeline`. This endpoint only supports keyset pagination.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCiUserPipeline"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCiUserPipeline?> GetAsync(Action<RequestConfiguration<global::Soenneker.GitLab.OpenApiClient.Api.V4.Pipelines.PipelinesRequestBuilder.PipelinesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCiUserPipeline> GetAsync(Action<RequestConfiguration<global::Soenneker.GitLab.OpenApiClient.Api.V4.Pipelines.PipelinesRequestBuilder.PipelinesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCiUserPipeline>(requestInfo, global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesCiUserPipeline.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lists recently created pipelines across all projects that were triggered by the authenticated user. By default, child pipelines are not included in the results. To return child pipelines, set `source` to `parent_pipeline`. This endpoint only supports keyset pagination.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.GitLab.OpenApiClient.Api.V4.Pipelines.PipelinesRequestBuilder.PipelinesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.GitLab.OpenApiClient.Api.V4.Pipelines.PipelinesRequestBuilder.PipelinesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Pipelines.PipelinesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.Pipelines.PipelinesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.GitLab.OpenApiClient.Api.V4.Pipelines.PipelinesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Lists recently created pipelines across all projects that were triggered by the authenticated user. By default, child pipelines are not included in the results. To return child pipelines, set `source` to `parent_pipeline`. This endpoint only supports keyset pagination.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PipelinesRequestBuilderGetQueryParameters 
        {
            /// <summary>Return pipelines created after the specified datetime. Format: ISO 8601 YYYY-MM-DDTHH:MM:SSZ</summary>
            [QueryParameter("created_after")]
            public DateTimeOffset? CreatedAfter { get; set; }
            /// <summary>Return pipelines created before the specified datetime. Format: ISO 8601 YYYY-MM-DDTHH:MM:SSZ</summary>
            [QueryParameter("created_before")]
            public DateTimeOffset? CreatedBefore { get; set; }
            /// <summary>Cursor for obtaining the next set of records</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
            /// <summary>Return pipelines ordered by `created_at`</summary>
            [QueryParameter("order_by")]
            public global::Soenneker.GitLab.OpenApiClient.Models.CreatedAtOrderBy? OrderBy { get; set; }
            /// <summary>Number of items per page</summary>
            [QueryParameter("per_page")]
            public int? PerPage { get; set; }
            /// <summary>Return pipelines sorted in `desc` order</summary>
            [QueryParameter("sort")]
            public global::Soenneker.GitLab.OpenApiClient.Models.DescSort? Sort { get; set; }
            /// <summary>The source of pipelines</summary>
            [QueryParameter("source")]
            public global::Soenneker.GitLab.OpenApiClient.Models.GetApiV4PipelinesSourceParameter? Source { get; set; }
        }
    }
}
#pragma warning restore CS0618
