// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Api.V4.Projects.Item.Deployments
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrder_byQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "iid")]
        #pragma warning disable CS1591
        Iid,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        Created_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        Updated_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "finished_at")]
        #pragma warning disable CS1591
        Finished_at,
        #pragma warning restore CS1591
    }
}
