// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.GitLab.OpenApiClient.Api.V4.Projects.Item.Service_accounts.Item.Personal_access_tokens
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetStateQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "inactive")]
        #pragma warning disable CS1591
        Inactive,
        #pragma warning restore CS1591
    }
}
