// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.GitLab.OpenApiClient.Api.V4.Runners.Router.Discovery;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.GitLab.OpenApiClient.Api.V4.Runners.Router
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\runners\router
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RouterRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The discovery property</summary>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.Runners.Router.Discovery.DiscoveryRequestBuilder Discovery
        {
            get => new global::Soenneker.GitLab.OpenApiClient.Api.V4.Runners.Router.Discovery.DiscoveryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Runners.Router.RouterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RouterRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/runners/router", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Runners.Router.RouterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RouterRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/runners/router", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
