// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.GitLab.OpenApiClient.Api.V4.Projects.Item.Packages.Helm.Item.Charts.WithFile_nameTgz;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.GitLab.OpenApiClient.Api.V4.Projects.Item.Packages.Helm.Item.Charts
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\projects\{-id}\packages\helm\{channel}\charts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChartsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Projects.Item.Packages.Helm.Item.Charts.ChartsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChartsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/projects/{%2Did}/packages/helm/{channel}/charts", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Projects.Item.Packages.Helm.Item.Charts.ChartsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChartsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/projects/{%2Did}/packages/helm/{channel}/charts", rawUrl)
        {
        }
        /// <summary>
        /// Builds and executes requests for operations under \api\v4\projects\{-id}\packages\helm\{channel}\charts\{file_name}.tgz
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Projects.Item.Packages.Helm.Item.Charts.WithFile_nameTgz.WithFile_nameTgzRequestBuilder"/></returns>
        /// <param name="file_name">Helm package file name</param>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.Projects.Item.Packages.Helm.Item.Charts.WithFile_nameTgz.WithFile_nameTgzRequestBuilder WithFile_nameTgz(string file_name)
        {
            if(string.IsNullOrEmpty(file_name)) throw new ArgumentNullException(nameof(file_name));
            return new global::Soenneker.GitLab.OpenApiClient.Api.V4.Projects.Item.Packages.Helm.Item.Charts.WithFile_nameTgz.WithFile_nameTgzRequestBuilder(PathParameters, RequestAdapter, file_name);
        }
    }
}
#pragma warning restore CS0618
