// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Milestones.Item;
using Soenneker.GitLab.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Milestones
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\groups\{id}\milestones
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MilestonesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.GitLab.OpenApiClient.api.v4.groups.item.milestones.item collection</summary>
        /// <param name="position">The ID of a group milestone</param>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Milestones.Item.WithMilestoneItemRequestBuilder"/></returns>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Milestones.Item.WithMilestoneItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("milestoneId", position);
                return new global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Milestones.Item.WithMilestoneItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Milestones.MilestonesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MilestonesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/groups/{id}/milestones{?iids,include_ancestors*,include_descendants*,include_parent_milestones*,page*,per_page*,search*,state*,title*,updated_after*,updated_before*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Milestones.MilestonesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MilestonesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/groups/{id}/milestones{?iids,include_ancestors*,include_descendants*,include_parent_milestones*,page*,per_page*,search*,state*,title*,updated_after*,updated_before*}", rawUrl)
        {
        }
        /// <summary>
        /// Lists all group milestones for a specified group.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMilestone"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMilestone?> GetAsync(Action<RequestConfiguration<global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Milestones.MilestonesRequestBuilder.MilestonesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMilestone> GetAsync(Action<RequestConfiguration<global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Milestones.MilestonesRequestBuilder.MilestonesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMilestone>(requestInfo, global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMilestone.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a milestone for the specified group.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMilestone"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMilestone?> PostAsync(global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyC1D0437D10F3 body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMilestone> PostAsync(global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyC1D0437D10F3 body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMilestone>(requestInfo, global::Soenneker.GitLab.OpenApiClient.Models.ApiEntitiesMilestone.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lists all group milestones for a specified group.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Milestones.MilestonesRequestBuilder.MilestonesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Milestones.MilestonesRequestBuilder.MilestonesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a milestone for the specified group.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyC1D0437D10F3 body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.GitLab.OpenApiClient.Models.RequestBodyC1D0437D10F3 body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Milestones.MilestonesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Milestones.MilestonesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.GitLab.OpenApiClient.Api.V4.Groups.Item.Milestones.MilestonesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Lists all group milestones for a specified group.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MilestonesRequestBuilderGetQueryParameters 
        {
            /// <summary>The IIDs of the milestones</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("iids")]
            public int?[]? Iids { get; set; }
#nullable restore
#else
            [QueryParameter("iids")]
            public int?[] Iids { get; set; }
#endif
            /// <summary>Include milestones from all parent groups. Mutually exclusive with `include_parent_milestones`.</summary>
            [QueryParameter("include_ancestors")]
            public bool? IncludeAncestors { get; set; }
            /// <summary>Include milestones from all subgroups and subprojects</summary>
            [QueryParameter("include_descendants")]
            public bool? IncludeDescendants { get; set; }
            /// <summary>Deprecated: see `include_ancestors`. Mutually exclusive with `include_ancestors`.</summary>
            [QueryParameter("include_parent_milestones")]
            public bool? IncludeParentMilestones { get; set; }
            /// <summary>Current page number</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>Number of items per page</summary>
            [QueryParameter("per_page")]
            public int? PerPage { get; set; }
            /// <summary>The search criteria for the title or description of the milestone</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search")]
            public string? Search { get; set; }
#nullable restore
#else
            [QueryParameter("search")]
            public string Search { get; set; }
#endif
            /// <summary>Return &quot;active&quot;, &quot;closed&quot;, or &quot;all&quot; milestones</summary>
            [QueryParameter("state")]
            public global::Soenneker.GitLab.OpenApiClient.Models.GetApiV4GroupsIdMilestonesStateParameter? State { get; set; }
            /// <summary>The title of the milestones</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("title")]
            public string? Title { get; set; }
#nullable restore
#else
            [QueryParameter("title")]
            public string Title { get; set; }
#endif
            /// <summary>Return milestones updated after the specified datetime. Format: ISO 8601 YYYY-MM-DDTHH:MM:SSZ</summary>
            [QueryParameter("updated_after")]
            public DateTimeOffset? UpdatedAfter { get; set; }
            /// <summary>Return milestones updated before the specified datetime. Format: ISO 8601 YYYY-MM-DDTHH:MM:SSZ</summary>
            [QueryParameter("updated_before")]
            public DateTimeOffset? UpdatedBefore { get; set; }
        }
    }
}
#pragma warning restore CS0618
